In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
url = "anime.csv"
anime = pd.read_csv(url)
anime.head()

MAL_ID                             Name Score  \
0       1                     Cowboy Bebop  8.78   
1       5  Cowboy Bebop: Tengoku no Tobira  8.39   
2       6                           Trigun  8.24   
3       7               Witch Hunter Robin  7.27   
4       8                   Bouken Ou Beet  6.98   

                                              Genres            English name  \
0    Action, Adventure, Comedy, Drama, Sci-Fi, Space            Cowboy Bebop   
1              Action, Drama, Mystery, Sci-Fi, Space  Cowboy Bebop:The Movie   
2  Action, Sci-Fi, Adventure, Comedy, Drama, Shounen                  Trigun   
3  Action, Mystery, Police, Supernatural, Drama, ...      Witch Hunter Robin   
4          Adventure, Fantasy, Shounen, Supernatural  Beet the Vandel Buster   

                      Japanese name   Type Episodes  \
0                         カウボーイビバップ     TV       26   
1                    カウボーイビバップ 天国の扉  Movie        1   
2                             トライガン     TV       26   
3  Witch Hunter ROBIN (ウイッチハンターロビン)     TV       26   
4                            冒険王ビィト     TV       52   

                          Aired    Premiered  ...  Score-10   Score-9  \
0   Apr 3, 1998 to Apr 24, 1999  Spring 1998  ...  229170.0  182126.0   
1                   Sep 1, 2001      Unknown  ...   30043.0   49201.0   
2   Apr 1, 1998 to Sep 30, 1998  Spring 1998  ...   50229.0   75651.0   
3   Jul 2, 2002 to Dec 24, 2002  Summer 2002  ...    2182.0    4806.0   
4  Sep 30, 2004 to Sep 29, 2005    Fall 2004  ...     312.0     529.0   

    Score-8  Score-7  Score-6 Score-5 Score-4  Score-3  Score-2  Score-1  
0  131625.0  62330.0  20688.0  8904.0  3184.0   1357.0    741.0   1580.0  
1   49505.0  22632.0   5805.0  1877.0   577.0    221.0    109.0    379.0  
2   86142.0  49432.0  15376.0  5838.0  1965.0    664.0    316.0    533.0  
3   10128.0  11618.0   5709.0  2920.0  1083.0    353.0    164.0    131.0  
4    1242.0   1713.0   1068.0   634.0   265.0     83.0     50.0     27.0  

[5 rows x 35 columns]

In [3]:
url = "anime2.csv"
anime_num = pd.read_csv(url)
anime_num = anime_num.drop(columns=["Unnamed: 0"], axis=1)
anime_num.head()

Score  Episodes  Aired  Duration  Popularity  Members  Favorites  Watching  \
0   8.78        26     25        24          39  1251960      61971    105808   
1   8.39         1     22       115         518   273145       1174      4143   
2   8.24        26     25        24         201   558913      12944     29113   
3   7.27        26     21        25        1467    94683        587      4300   
4   6.98        52     19        23        4369    13224         18       642   

   Completed  On-Hold  ...  OVA  Movie  Special  ONA  G - All Ages  \
0     718161    71513  ...  0.0    0.0      0.0  0.0           0.0   
1     208333     1935  ...  0.0    1.0      0.0  0.0           0.0   
2     343492    25465  ...  0.0    0.0      0.0  0.0           0.0   
3      46165     5121  ...  0.0    0.0      0.0  0.0           0.0   
4       7314      766  ...  0.0    0.0      0.0  0.0           0.0   

   PG-13 - Teens 13 or older  PG - Children  Rx - Hentai  \
0                        0.0            0.0          0.0   
1                        0.0            0.0          0.0   
2                        1.0            0.0          0.0   
3                        1.0            0.0          0.0   
4                        0.0            1.0          0.0   

   R - 17+ (violence & profanity)  R+ - Mild Nudity  
0                             1.0               0.0  
1                             1.0               0.0  
2                             0.0               0.0  
3                             0.0               0.0  
4                             0.0               0.0  

[5 rows x 80 columns]

In [4]:
url = "users2.csv"
users = pd.read_csv(url)
user_ids = users["user_id"].apply(str)
users = users.drop(["user_id"], axis=1)
users.head()

Unnamed: 0  1535  16498  11757  5114  4224  6547  1575  9253  20  ...  \
0           0     0      0      0     0     0     0     0     0   0  ...   
1           1     9     10      5    10     9     6    10    10  10  ...   
2           2    10      9      0     0     0     0     9     9   9  ...   
3           3     0      0      0     0     8     8     8     9   0  ...   
4           4    10      0      0     0     9     0    10     0   0  ...   

   48470  48481  47623  44376  48480  48427  47634  48391  41750  41250  
0      0      0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0      0      0  

[5 rows x 17563 columns]

In [14]:
cosine_simU = cosine_similarity(users, users)
print(cosine_simU)

In [15]:
indicesU = pd.Series(user_ids)

def recomC(title, cosine_sim):
    recommended_users = []
    idx = indicesU[indicesU == title].index[0]
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_users.append([list(user_ids)[i], i])
        
    return recommended_users

def recUC(search, cosine_sim=cosine_simU):
    top = recomC(search, cosine_sim)[0]
    ind = indicesU[indicesU==search].index[0]
    ti = users.loc[[ind, top[1]]]
    ti = ti.sort_values(by = top[1], axis = 1, ascending=False)
    exc = [column for column in ti.columns if ti.loc[top[1]][column] > 0]
    ti2 = ti.sort_values(by = ind, axis = 1, ascending=False)
    exc2 = [column for column in ti2.columns if ti2.loc[ind][column] > 0]
    return [x for x in exc2 if x not in exc][:10]

def recommendUC(anime_ids):
    names = []
    for animes in anime_ids:
        names.append(anime[anime["MAL_ID"]==int(animes)]["Name"].values[0])
    return names

def recommendUserC(user):
    ids = recUC(user)
    return recommendUC(ids)

recommendUserC("2.0")

['Hajime no Ippo',
 'Detective Conan',
 'High School DxD New',
 'Eyeshield 21',
 'Naruto',
 'Tennis no Ouji-sama',
 'Katekyo Hitman Reborn!',
 'One Punch Man',
 'One Punch Man 2nd Season',
 'Boku no Hero Academia 2nd Season']

In [5]:
cosine_simA = cosine_similarity(anime_num, anime_num)
print(cosine_simA)

[[1.         0.98665848 0.99885649 ... 0.50642115 0.08330723 0.01873247]
 [0.98665848 1.         0.99243379 ... 0.45361022 0.07591212 0.01820057]
 [0.99885649 0.99243379 1.         ... 0.4991576  0.08233921 0.01872441]
 ...
 [0.50642115 0.45361022 0.4991576  ... 1.         0.80903078 0.75575516]
 [0.08330723 0.07591212 0.08233921 ... 0.80903078 1.         0.99633013]
 [0.01873247 0.01820057 0.01872441 ... 0.75575516 0.99633013 1.        ]]


In [6]:
indicesA = pd.Series(anime["Name"])

def recommendAnimeC(title, cosine_sim = cosine_simA):
    recommended_anime = []
    idx = indicesA[indicesA == title].index[0]
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_anime.append(list(anime['Name'])[i])
        
    return recommended_anime

recommendAnimeC('Cowboy Bebop')

['Hajime no Ippo',
 'Great Teacher Onizuka',
 'Psycho-Pass',
 'Violet Evergarden',
 'Durarara!!',
 'Higurashi no Naku Koro ni',
 'Kekkai Sensen',
 'Slam Dunk',
 'Hyouka',
 'Hellsing Ultimate']

In [16]:
recommendAnimeC('Jujutsu Kaisen (TV)')

['Shingeki no Kyojin: The Final Season',
 'Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari',
 'Horimiya',
 'Kaifuku Jutsushi no Yarinaoshi',
 'Mushoku Tensei: Isekai Ittara Honki Dasu',
 'SK∞',
 'Ore dake Haireru Kakushi Dungeon',
 'Black Clover',
 'Kumo Desu ga, Nani ka?',
 'Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2']

In [17]:
recommendUserC("823.0")

['Mononoke Hime',
 'Samurai Champloo',
 'Shirobako',
 'Cowboy Bebop',
 'Bakuman. 2nd Season',
 'Uchuu Kyoudai',
 'So Ra No Wo To',
 'Cowboy Bebop: Tengoku no Tobira',
 'Koukaku Kidoutai 2.0',
 'Panty & Stocking with Garterbelt']

In [57]:
recommendAnime('Mononoke Hime')

['Mirai Nikki OVA',
 'Berserk: Ougon Jidai-hen III - Kourin',
 'Tenkuu no Shiro Laputa',
 'Neon Genesis Evangelion: The End of Evangelion',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku OVA',
 'Kono Subarashii Sekai ni Shukufuku wo! 2: Kono Subarashii Geijutsu ni Shukufuku wo!',
 'Grisaia no Meikyuu: Caprice no Mayu 0',
 'Date A Live II: Kurumi Star Festival',
 'Date A Live: Date to Date',
 'Tokyo Ghoul: "Jack"']

In [9]:
from sklearn.metrics.pairwise import euclidean_distances

In [18]:
euclideanU = euclidean_distances(users, users)
print(euclideanU)

[[   0.           99.95498987   80.54191455 ... 1000.50987002
  1002.27990103 1005.22136865]
 [  99.95498987    0.           95.27853903 ...  999.89749475
  1001.07042709 1006.87884077]
 [  80.54191455   95.27853903    0.         ...  998.3020585
  1000.02499969 1004.06922072]
 ...
 [1000.50987002  999.89749475  998.3020585  ...    0.
    84.32674546  122.80879447]
 [1002.27990103 1001.07042709 1000.02499969 ...   84.32674546
     0.          128.19126335]
 [1005.22136865 1006.87884077 1004.06922072 ...  122.80879447
   128.19126335    0.        ]]


In [19]:
indicesU = pd.Series(user_ids)

def recomE(title, euclidean):
    recommended_users = []
    idx = indicesU[indicesU == title].index[0]
    score_series = pd.Series(euclidean[idx]).sort_values(ascending = True)
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_users.append([list(user_ids)[i], i])
        
    return recommended_users

def recUE(search, euclidean=euclideanU):
    top = recomE(search, euclidean)[0]
    ind = indicesU[indicesU==search].index[0]
    ti = users.loc[[ind, top[1]]]
    ti = ti.sort_values(by = top[1], axis = 1, ascending=False)
    exc = [column for column in ti.columns if ti.loc[top[1]][column] > 0]
    ti2 = ti.sort_values(by = ind, axis = 1, ascending=False)
    exc2 = [column for column in ti2.columns if ti2.loc[ind][column] > 0]
    return [x for x in exc2 if x not in exc][:10]

def recommendUE(anime_ids):
    names = []
    for animes in anime_ids:
        names.append(anime[anime["MAL_ID"]==int(animes)]["Name"].values[0])
    return names

def recommendUserE(user):
    ids = recUE(user)
    return recommendUE(ids)

recommendUserE("2.0")

['Hajime no Ippo',
 'Death Note',
 'Code Geass: Hangyaku no Lelouch R2',
 'Hunter x Hunter (2011)',
 'Detective Conan',
 'Shokugeki no Souma',
 'One Punch Man',
 'One Piece',
 'Boku no Hero Academia 2nd Season',
 'Nanatsu no Taizai']

In [20]:
recommendUserC("2.0")

['Hajime no Ippo',
 'Detective Conan',
 'High School DxD New',
 'Eyeshield 21',
 'Naruto',
 'Tennis no Ouji-sama',
 'Katekyo Hitman Reborn!',
 'One Punch Man',
 'One Punch Man 2nd Season',
 'Boku no Hero Academia 2nd Season']

In [7]:
anime_numN = anime_num
for column in anime_numN.columns:
    anime_numN[column] = anime_numN[column]  / anime_numN[column].abs().max()
anime_numN.head()

Score  Episodes     Aired  Duration  Popularity   Members  Favorites  \
0  0.955386  0.004167  0.235849  0.143713    0.002220  0.483466   0.336956   
1  0.912949  0.000160  0.207547  0.688623    0.029490  0.105480   0.006383   
2  0.896627  0.004167  0.235849  0.143713    0.011443  0.215834   0.070381   
3  0.791077  0.004167  0.198113  0.149701    0.083518  0.036563   0.003192   
4  0.759521  0.008333  0.179245  0.137725    0.248733  0.005107   0.000098   

   Watching  Completed   On-Hold  ...  OVA  Movie  Special  ONA  G - All Ages  \
0  0.119243   0.329041  0.380552  ...  0.0    0.0      0.0  0.0           0.0   
1  0.004669   0.095452  0.010297  ...  0.0    1.0      0.0  0.0           0.0   
2  0.032810   0.157378  0.135511  ...  0.0    0.0      0.0  0.0           0.0   
3  0.004846   0.021152  0.027251  ...  0.0    0.0      0.0  0.0           0.0   
4  0.000724   0.003351  0.004076  ...  0.0    0.0      0.0  0.0           0.0   

   PG-13 - Teens 13 or older  PG - Children  Rx - Hentai  \
0                        0.0            0.0          0.0   
1                        0.0            0.0          0.0   
2                        1.0            0.0          0.0   
3                        1.0            0.0          0.0   
4                        0.0            1.0          0.0   

   R - 17+ (violence & profanity)  R+ - Mild Nudity  
0                             1.0               0.0  
1                             1.0               0.0  
2                             0.0               0.0  
3                             0.0               0.0  
4                             0.0               0.0  

[5 rows x 80 columns]

In [10]:
euclideanA2 = euclidean_distances(anime_numN, anime_numN)
print(euclideanA2)

[[0.         2.48742776 2.53638427 ... 4.03792277 3.36822837 3.51411682]
 [2.48742776 0.         3.37406037 ... 3.80177352 3.93201148 3.53004994]
 [2.53638427 3.37406037 0.         ... 4.15561058 2.50738583 3.35985987]
 ...
 [4.03792277 3.80177352 4.15561058 ... 0.         3.60562898 3.46420072]
 [3.36822837 3.93201148 2.50738583 ... 3.60562898 0.         3.00000107]
 [3.51411682 3.53004994 3.35985987 ... 3.46420072 3.00000107 0.        ]]


In [11]:
indicesA = pd.Series(anime["Name"])

def recommendAnimeE(title, euclidean = euclideanA2):
    recommended_anime = []
    idx = indicesA[indicesA == title].index[0]
    score_series = pd.Series(euclidean[idx]).sort_values(ascending = True)
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_anime.append(list(anime['Name'])[i])
        
    return recommended_anime

recommendAnimeE('Cowboy Bebop')

['Cowboy Bebop: Yose Atsume Blues',
 'Mobile Suit Gundam: Iron-Blooded Orphans',
 'Mobile Suit Gundam: Iron-Blooded Orphans 2nd Season',
 'Galilei Donna',
 'Ginga Tetsudou Monogatari',
 'Ginga Tetsudou Monogatari: Eien e no Bunkiten',
 'Michiko to Hatchin',
 'Akudama Drive',
 'Mobile Suit Gundam 00',
 'Aldnoah.Zero 2nd Season']

In [12]:
recommendAnimeE('One Piece')

['Hunter x Hunter (2011)',
 'Naruto: Shippuuden',
 'Bleach',
 'Fairy Tail',
 'Dragon Ball Super',
 'Dragon Ball Z',
 'Naruto',
 'Hunter x Hunter',
 'Black Clover',
 'Dragon Ball Kai']

In [13]:
recommendAnimeE('Death Note')

['Mirai Nikki',
 'Boku dake ga Inai Machi',
 'Yakusoku no Neverland',
 'Yakusoku no Neverland 2nd Season',
 'Munou na Nana',
 'Death Note: Rewrite',
 'Yakusoku no Neverland 2nd Season: Michishirube',
 'Higurashi no Naku Koro ni Kai',
 'Kakegurui',
 'Zankyou no Terror']

In [93]:
recommendAnimeE("Mahoutsukai no Yome")

['Mahoutsukai no Yome: Hoshi Matsu Hito',
 'Maoujou de Oyasumi',
 'Tensura Nikki: Tensei shitara Slime Datta Ken',
 'Namiuchigiwa no Muromi-san',
 'Mahoutsukai ni Taisetsu na Koto',
 'Mahoutsukai no Yome Recap',
 'Kagi Hime Monogatari: Eikyuu Alice Rondo',
 'Mahoutsukai no Yome: Gakuin-hen',
 'Mahoutsukai no Yome: Nishi no Shounen to Seiran no Kishi',
 'Magi: The Labyrinth of Magic']