In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
url = "users.csv"
users = pd.read_csv(url)
users.head()

user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4
3        0      4898       0                1                 1
4        0        21      10                1                 0

In [3]:
names = users["user_id"].value_counts()
names

20807     17546
140590    17534
281232    17533
147331    17526
131988    17520
          ...  
259248        1
259247        1
345120        1
287410        1
307120        1
Name: user_id, Length: 325770, dtype: int64

In [4]:
len(names)

325770

In [6]:
userg = pd.DataFrame(sorted(names.index), columns=["user_id"])
userg.head()

user_id
0        0
1        1
2        2
3        3
4        4

In [5]:
animes = users["anime_id"].value_counts()
animes

1535     238790
16498    216767
11757    209919
5114     201611
4224     196190
          ...  
48427         1
47634         1
48391         1
41750         1
41250         1
Name: anime_id, Length: 17562, dtype: int64

In [6]:
userd = pd.DataFrame(columns=animes.index)
userd.head()

Empty DataFrame
Columns: [1535, 16498, 11757, 5114, 4224, 6547, 1575, 9253, 20, 10620, 30276, 19815, 22319, 226, 2167, 5081, 20507, 6746, 199, 2001, 9919, 2904, 32281, 11111, 269, 31964, 3588, 9989, 8074, 30, 13601, 23273, 6702, 1735, 31240, 31043, 849, 1, 121, 18679, 21881, 22199, 9756, 15809, 25777, 10087, 12189, 22535, 11061, 14813, 28223, 14741, 30831, 28851, 4181, 10793, 5680, 21, 33486, 23755, 13759, 2025, 6880, 28171, 1689, 24833, 7054, 27899, 934, 18153, 205, 356, 28121, 28999, 4898, 2251, 11617, 853, 431, 164, 918, 32182, 18897, 2966, 23283, 29803, 17265, 14227, 2236, 4654, 1195, 38000, 889, 30503, 33352, 20583, 1210, 8769, 6045, 10719, ...]
Index: []

[0 rows x 17562 columns]

In [18]:
userd.loc[len(userd)] = [0]*17562
userd.head()

1535   16498  11757  5114   4224   6547   1575   9253   20     10620  ...  \
0      0      0      0      0      0      0      0      0      0      0  ...   
1      0      0      0      0      0      0      0      0      0      0  ...   

   48470  48481  47623  44376  48480  48427  47634  48391  41750  41250  
0      0      0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0      0      0  

[2 rows x 17562 columns]

In [28]:
li = [0]*17562
for i in range(325770):
    if (i % 5000 == 0):
        print(i)
    userd.loc[i] = li
userd.tail()

0


KeyboardInterrupt: 

In [9]:
userd["user_id"] = names.index[:30000]
userd.head()

1535 16498 11757 5114 4224 6547 1575 9253   20 10620  ... 48481 47623 44376  \
0  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  ...   NaN   NaN   NaN   
1  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  ...   NaN   NaN   NaN   
2  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  ...   NaN   NaN   NaN   
3  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  ...   NaN   NaN   NaN   
4  NaN   NaN   NaN  NaN  NaN  NaN  NaN  NaN  NaN   NaN  ...   NaN   NaN   NaN   

  48480 48427 47634 48391 41750 41250 user_id  
0   NaN   NaN   NaN   NaN   NaN   NaN   20807  
1   NaN   NaN   NaN   NaN   NaN   NaN  140590  
2   NaN   NaN   NaN   NaN   NaN   NaN  281232  
3   NaN   NaN   NaN   NaN   NaN   NaN  147331  
4   NaN   NaN   NaN   NaN   NaN   NaN  131988  

[5 rows x 17563 columns]

In [10]:
prev = -1
use = 0
for i, row in users.iterrows():
    if row["user_id"] != prev:
        if (use % 100 == 0):
            print(use)
        if (use >= 1000):
            print(f"First {use} users done")
            break;
        use += 1
        userd.loc[(use-1), 'user_id'] = row['user_id']
        ind = userd.index[userd['user_id'] == row["user_id"]].tolist()[0]
        prev = row["user_id"]
    userd.at[ind, row["anime_id"]] = row["rating"]

0
5000
10000
15000
20000
25000
30000
35000
40000
45000
50000
55000
60000
65000
70000
75000
80000
85000
90000
95000
100000
105000
110000
115000
120000
125000
130000
135000
140000
145000
150000
155000
160000
165000
170000
175000
180000
185000
190000
195000
200000
205000
210000
215000
220000
225000
230000
235000
240000
245000
250000
255000
260000
265000
270000
275000
280000
285000
290000
295000
300000
305000
310000
315000
320000
325000
330000
335000
340000
345000
First 1000 users done


In [9]:
userSmall = userd
userSmall.head()

1535 16498 11757 5114 4224 6547 1575 9253   20 10620  ... 48481 47623 44376  \
0    0   NaN   NaN    0  NaN  NaN  NaN  NaN    0   NaN  ...   NaN   NaN   NaN   
1    9    10     5   10    9    6   10   10   10   NaN  ...   NaN   NaN   NaN   
2   10     9     0    0    0  NaN    9    9    9     8  ...   NaN   NaN   NaN   
3  NaN   NaN   NaN    0    8    8    8    9  NaN     8  ...   NaN   NaN   NaN   
4   10   NaN   NaN    0    9  NaN   10  NaN  NaN   NaN  ...   NaN   NaN   NaN   

  48480 48427 47634 48391 41750 41250 user_id  
0   NaN   NaN   NaN   NaN   NaN   NaN     0.0  
1   NaN   NaN   NaN   NaN   NaN   NaN     1.0  
2   NaN   NaN   NaN   NaN   NaN   NaN     2.0  
3   NaN   NaN   NaN   NaN   NaN   NaN     3.0  
4   NaN   NaN   NaN   NaN   NaN   NaN     4.0  

[5 rows x 17563 columns]

In [11]:
userSmall.tail()

1535 16498 11757 5114 4224 6547 1575 9253 20 10620  ... 48481 47623 44376  \
995  NaN     8     8    0  NaN  NaN    6    0  9   NaN  ...   NaN   NaN   NaN   
996   10     8     1  NaN  NaN  NaN  NaN   10  0   NaN  ...   NaN   NaN   NaN   
997   10    10   NaN   10  NaN  NaN  NaN  NaN  8   NaN  ...   NaN   NaN   NaN   
998    9     0    10   10    9    8    0   10  9     0  ...   NaN   NaN   NaN   
999   10   NaN   NaN  NaN  NaN  NaN  NaN  NaN  9   NaN  ...   NaN   NaN   NaN   

    48480 48427 47634 48391 41750 41250 user_id  
995   NaN   NaN   NaN   NaN   NaN   NaN  1085.0  
996   NaN   NaN   NaN   NaN   NaN   NaN  1086.0  
997   NaN   NaN   NaN   NaN   NaN   NaN  1087.0  
998   NaN   NaN   NaN   NaN   NaN   NaN  1088.0  
999   NaN   NaN   NaN   NaN   NaN   NaN  1089.0  

[5 rows x 17563 columns]

In [12]:
userd.tail()

1535 16498 11757 5114 4224 6547 1575 9253 20 10620  ... 48481 47623 44376  \
995  NaN     8     8    0  NaN  NaN    6    0  9   NaN  ...   NaN   NaN   NaN   
996   10     8     1  NaN  NaN  NaN  NaN   10  0   NaN  ...   NaN   NaN   NaN   
997   10    10   NaN   10  NaN  NaN  NaN  NaN  8   NaN  ...   NaN   NaN   NaN   
998    9     0    10   10    9    8    0   10  9     0  ...   NaN   NaN   NaN   
999   10   NaN   NaN  NaN  NaN  NaN  NaN  NaN  9   NaN  ...   NaN   NaN   NaN   

    48480 48427 47634 48391 41750 41250 user_id  
995   NaN   NaN   NaN   NaN   NaN   NaN  1085.0  
996   NaN   NaN   NaN   NaN   NaN   NaN  1086.0  
997   NaN   NaN   NaN   NaN   NaN   NaN  1087.0  
998   NaN   NaN   NaN   NaN   NaN   NaN  1088.0  
999   NaN   NaN   NaN   NaN   NaN   NaN  1089.0  

[5 rows x 17563 columns]

In [13]:
len(userd)

1000

In [14]:
len(userSmall)

1000

In [16]:
userd = userd.fillna(0)
userd.tail()

1535  16498  11757  5114  4224  6547  1575  9253  20  10620  ...  48481  \
995     0      8      8     0     0     0     6     0   9      0  ...      0   
996    10      8      1     0     0     0     0    10   0      0  ...      0   
997    10     10      0    10     0     0     0     0   8      0  ...      0   
998     9      0     10    10     9     8     0    10   9      0  ...      0   
999    10      0      0     0     0     0     0     0   9      0  ...      0   

     47623  44376  48480  48427  47634  48391  41750  41250  user_id  
995      0      0      0      0      0      0      0      0   1085.0  
996      0      0      0      0      0      0      0      0   1086.0  
997      0      0      0      0      0      0      0      0   1087.0  
998      0      0      0      0      0      0      0      0   1088.0  
999      0      0      0      0      0      0      0      0   1089.0  

[5 rows x 17563 columns]

In [17]:
user_ids = userd["user_id"]
user_ids.head()

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
Name: user_id, dtype: float64

In [26]:
user_id2 = user_ids.apply(str)
user_id2.head()

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
Name: user_id, dtype: object

In [19]:
userd = userd.drop(["user_id"], axis=1)
userd.tail()

1535   16498  11757  5114   4224   6547   1575   9253   20     10620  \
995      0      8      8      0      0      0      6      0      9      0   
996     10      8      1      0      0      0      0     10      0      0   
997     10     10      0     10      0      0      0      0      8      0   
998      9      0     10     10      9      8      0     10      9      0   
999     10      0      0      0      0      0      0      0      9      0   

     ...  48470  48481  47623  44376  48480  48427  47634  48391  41750  41250  
995  ...      0      0      0      0      0      0      0      0      0      0  
996  ...      0      0      0      0      0      0      0      0      0      0  
997  ...      0      0      0      0      0      0      0      0      0      0  
998  ...      0      0      0      0      0      0      0      0      0      0  
999  ...      0      0      0      0      0      0      0      0      0      0  

[5 rows x 17562 columns]

In [20]:
cosine_sim = cosine_similarity(userd, userd)
print(cosine_sim)

[[1.         0.06635511 0.0561149  ... 0.05033583 0.04341036 0.14038247]
 [0.06635511 1.         0.2387879  ... 0.37802018 0.41339438 0.06060322]
 [0.0561149  0.2387879  1.         ... 0.22495875 0.20398297 0.07709361]
 ...
 [0.05033583 0.37802018 0.22495875 ... 1.         0.32951568 0.04285078]
 [0.04341036 0.41339438 0.20398297 ... 0.32951568 1.         0.04886832]
 [0.14038247 0.06060322 0.07709361 ... 0.04285078 0.04886832 1.        ]]


In [89]:
indices = pd.Series(user_id2)

def recom(title, cosine_sim = cosine_sim):
    recommended_users = []
    idx = indices[indices == title].index[0]
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_users.append([list(user_id2)[i], i])
        
    return recommended_users

def recommend(search, cosine_sim=cosine_sim):
    top = recom(search, cosine_sim)[0]
    ind = indices[indices==search].index[0]
    ti = userd.loc[[ind, top[1]]]
    ti = ti.sort_values(by = top[1], axis = 1, ascending=False)
    exc = [column for column in ti.columns if ti.loc[top[1]][column] > 0]
    ti2 = ti.sort_values(by = ind, axis = 1, ascending=False)
    exc2 = [column for column in ti2.columns if ti2.loc[ind][column] > 0]
    return [x for x in exc2 if x not in exc][:10]

recommend("2.0")

[263, 235, 5040, 15, 1735, 1604, 34134, 22, 270, 7593]

In [31]:
print(indices[indices=="2.0"].index[0])
print(indices[indices=="1069.0"].index[0])

2
980


In [90]:
recommend("0.0")

[235, 578, 242, 415, 21, 1571, 3125, 356, 121, 67]

In [34]:
r1 = userd.iloc[[2]]
r1

1535   16498  11757  5114   4224   6547   1575   9253   20     10620  ...  \
2     10      9      0      0      0      0      9      9      9      8  ...   

   48470  48481  47623  44376  48480  48427  47634  48391  41750  41250  
2      0      0      0      0      0      0      0      0      0      0  

[1 rows x 17562 columns]

In [35]:
r2 = userd.iloc[[980]]
r2

1535   16498  11757  5114   4224   6547   1575   9253   20     10620  \
980      8      5      4      7      6      8      9     10      7      8   

     ...  48470  48481  47623  44376  48480  48427  47634  48391  41750  41250  
980  ...      0      0      0      0      0      0      0      0      0      0  

[1 rows x 17562 columns]

In [49]:
recommend("0.0")

[['521.0', 472],
 ['530.0', 481],
 ['247.0', 221],
 ['797.0', 728],
 ['329.0', 299],
 ['616.0', 560],
 ['861.0', 788],
 ['667.0', 609],
 ['101.0', 96],
 ['88.0', 85]]

In [38]:
userSmall.tail()

1535 16498 11757 5114 4224 6547 1575 9253 20 10620  ... 48481 47623 44376  \
995  NaN     8     8    0  NaN  NaN    6    0  9   NaN  ...   NaN   NaN   NaN   
996   10     8     1  NaN  NaN  NaN  NaN   10  0   NaN  ...   NaN   NaN   NaN   
997   10    10   NaN   10  NaN  NaN  NaN  NaN  8   NaN  ...   NaN   NaN   NaN   
998    9     0    10   10    9    8    0   10  9     0  ...   NaN   NaN   NaN   
999   10   NaN   NaN  NaN  NaN  NaN  NaN  NaN  9   NaN  ...   NaN   NaN   NaN   

    48480 48427 47634 48391 41750 41250 user_id  
995   NaN   NaN   NaN   NaN   NaN   NaN  1085.0  
996   NaN   NaN   NaN   NaN   NaN   NaN  1086.0  
997   NaN   NaN   NaN   NaN   NaN   NaN  1087.0  
998   NaN   NaN   NaN   NaN   NaN   NaN  1088.0  
999   NaN   NaN   NaN   NaN   NaN   NaN  1089.0  

[5 rows x 17563 columns]

In [39]:
userSmall.to_csv("users2.csv")

In [45]:
user_id2[user_id2=="1069.0"].index[0]

980

In [40]:
userd.index[user_id2['user_id'] == "2.0"].tolist()[0]

KeyError: 'user_id'

In [80]:
ti = userd.loc[[2,980]]
ti

1535   16498  11757  5114   4224   6547   1575   9253   20     10620  \
2       10      9      0      0      0      0      9      9      9      8   
980      8      5      4      7      6      8      9     10      7      8   

     ...  48470  48481  47623  44376  48480  48427  47634  48391  41750  41250  
2    ...      0      0      0      0      0      0      0      0      0      0  
980  ...      0      0      0      0      0      0      0      0      0      0  

[2 rows x 17562 columns]

In [81]:
ti2 = ti.sort_values(by = 980, axis = 1, ascending=False)
ti2

37991  31933  2904   21     9253   37105  1      245    11061  28851  \
2        0      0     10      9      9      0      0      0     10      0   
980     10     10     10     10     10     10     10     10      9      9   

     ...  613    39194  30812  2722   10832  22583  37172  2325   1417   41250  
2    ...      0      0      0      0      0      0      0      0      0      0  
980  ...      0      0      0      0      0      0      0      0      0      0  

[2 rows x 17562 columns]

In [82]:
exc2 = [column for column in ti2.columns if ti2.loc[980][column] > 0]
exc2

[37991,
 31933,
 2904,
 21,
 9253,
 37105,
 1,
 245,
 11061,
 28851,
 1575,
 268,
 16918,
 28171,
 853,
 32182,
 1535,
 35760,
 37999,
 37510,
 31646,
 35788,
 33255,
 34612,
 32282,
 30276,
 6547,
 10620,
 523,
 20,
 2251,
 2001,
 23755,
 33486,
 5114,
 36456,
 30831,
 34577,
 38186,
 8525,
 24833,
 38101,
 38691,
 23273,
 26055,
 14719,
 15451,
 11617,
 38671,
 24703,
 22319,
 20899,
 31964,
 31240,
 4224,
 32937,
 35790,
 37086,
 30240,
 28121,
 25777,
 37349,
 37982,
 6746,
 34933,
 37779,
 38759,
 16498,
 28223,
 36407,
 11757,
 19815,
 31722]

In [63]:
exc = {column for column in ti2.columns if ti2.loc[2][column] > 0}
exc

{15,
 20,
 21,
 22,
 71,
 189,
 226,
 235,
 263,
 270,
 368,
 1535,
 1575,
 1604,
 1735,
 2904,
 3455,
 5040,
 5042,
 5762,
 7593,
 7661,
 8074,
 9253,
 10620,
 10851,
 11061,
 11499,
 14719,
 15451,
 16498,
 20899,
 22319,
 22535,
 23755,
 24703,
 26055,
 28171,
 28223,
 28961,
 29575,
 29786,
 30276,
 31580,
 31740,
 31964,
 32182,
 32872,
 33486,
 34134,
 34542,
 34599,
 34933,
 35028,
 35581,
 37086,
 38671}

In [83]:
len(exc)

57

In [84]:
len(exc2)

73

In [86]:
[x for x in exc if x not in exc2]

[263,
 235,
 1604,
 22,
 5040,
 270,
 34134,
 1735,
 15,
 5042,
 22535,
 368,
 189,
 29786,
 35028,
 35581,
 7661,
 3455,
 29575,
 226,
 71,
 7593,
 34542,
 5762,
 31740,
 32872,
 34599,
 28961,
 31580,
 11499,
 8074,
 10851]

In [75]:
print(list(exc2 - exc)[0])

4224
