In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def to_1D(series):
    return pd.Series([x for _list in series for x in _list])

In [2]:
url = "anime.csv"
anime = pd.read_csv(url)
anime.head()

MAL_ID                             Name Score  \
0       1                     Cowboy Bebop  8.78   
1       5  Cowboy Bebop: Tengoku no Tobira  8.39   
2       6                           Trigun  8.24   
3       7               Witch Hunter Robin  7.27   
4       8                   Bouken Ou Beet  6.98   

                                              Genres            English name  \
0    Action, Adventure, Comedy, Drama, Sci-Fi, Space            Cowboy Bebop   
1              Action, Drama, Mystery, Sci-Fi, Space  Cowboy Bebop:The Movie   
2  Action, Sci-Fi, Adventure, Comedy, Drama, Shounen                  Trigun   
3  Action, Mystery, Police, Supernatural, Drama, ...      Witch Hunter Robin   
4          Adventure, Fantasy, Shounen, Supernatural  Beet the Vandel Buster   

                      Japanese name   Type Episodes  \
0                         カウボーイビバップ     TV       26   
1                    カウボーイビバップ 天国の扉  Movie        1   
2                             トライガン     TV       26   
3  Witch Hunter ROBIN (ウイッチハンターロビン)     TV       26   
4                            冒険王ビィト     TV       52   

                          Aired    Premiered  ...  Score-10   Score-9  \
0   Apr 3, 1998 to Apr 24, 1999  Spring 1998  ...  229170.0  182126.0   
1                   Sep 1, 2001      Unknown  ...   30043.0   49201.0   
2   Apr 1, 1998 to Sep 30, 1998  Spring 1998  ...   50229.0   75651.0   
3   Jul 2, 2002 to Dec 24, 2002  Summer 2002  ...    2182.0    4806.0   
4  Sep 30, 2004 to Sep 29, 2005    Fall 2004  ...     312.0     529.0   

    Score-8  Score-7  Score-6 Score-5 Score-4  Score-3  Score-2  Score-1  
0  131625.0  62330.0  20688.0  8904.0  3184.0   1357.0    741.0   1580.0  
1   49505.0  22632.0   5805.0  1877.0   577.0    221.0    109.0    379.0  
2   86142.0  49432.0  15376.0  5838.0  1965.0    664.0    316.0    533.0  
3   10128.0  11618.0   5709.0  2920.0  1083.0    353.0    164.0    131.0  
4    1242.0   1713.0   1068.0   634.0   265.0     83.0     50.0     27.0  

[5 rows x 35 columns]

In [30]:
url = "anime2.csv"
anime_num = pd.read_csv(url)
anime_num = anime_num.drop(columns=["Unnamed: 0"], axis=1)
anime_num.head()

Score  Episodes  Aired  Duration  Popularity  Members  Favorites  Watching  \
0   8.78        26     25        24          39  1251960      61971    105808   
1   8.39         1     22       115         518   273145       1174      4143   
2   8.24        26     25        24         201   558913      12944     29113   
3   7.27        26     21        25        1467    94683        587      4300   
4   6.98        52     19        23        4369    13224         18       642   

   Completed  On-Hold  ...  OVA  Movie  Special  ONA  G - All Ages  \
0     718161    71513  ...  0.0    0.0      0.0  0.0           0.0   
1     208333     1935  ...  0.0    1.0      0.0  0.0           0.0   
2     343492    25465  ...  0.0    0.0      0.0  0.0           0.0   
3      46165     5121  ...  0.0    0.0      0.0  0.0           0.0   
4       7314      766  ...  0.0    0.0      0.0  0.0           0.0   

   PG-13 - Teens 13 or older  PG - Children  Rx - Hentai  \
0                        0.0            0.0          0.0   
1                        0.0            0.0          0.0   
2                        1.0            0.0          0.0   
3                        1.0            0.0          0.0   
4                        0.0            1.0          0.0   

   R - 17+ (violence & profanity)  R+ - Mild Nudity  
0                             1.0               0.0  
1                             1.0               0.0  
2                             0.0               0.0  
3                             0.0               0.0  
4                             0.0               0.0  

[5 rows x 80 columns]

In [8]:
url = "users2.csv"
users = pd.read_csv(url)
user_ids = users["user_id"].apply(str)
users = users.drop(["user_id"], axis=1)
users.head()

Unnamed: 0  1535  16498  11757  5114  4224  6547  1575  9253  20  ...  \
0           0     0      0      0     0     0     0     0     0   0  ...   
1           1     9     10      5    10     9     6    10    10  10  ...   
2           2    10      9      0     0     0     0     9     9   9  ...   
3           3     0      0      0     0     8     8     8     9   0  ...   
4           4    10      0      0     0     9     0    10     0   0  ...   

   48470  48481  47623  44376  48480  48427  47634  48391  41750  41250  
0      0      0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0      0      0  

[5 rows x 17563 columns]

In [46]:
cosine_simU = cosine_similarity(users, users)
print(cosine_simU)

[[1.         0.06635082 0.05608679 ... 0.00337878 0.00337279 0.01478031]
 [0.06635082 1.         0.23901254 ... 0.03671158 0.04344687 0.01768147]
 [0.05608679 0.23901254 1.         ... 0.04667182 0.04739545 0.03958738]
 ...
 [0.00337878 0.03671158 0.04667182 ... 1.         0.99644706 0.99250195]
 [0.00337279 0.04344687 0.04739545 ... 0.99644706 1.         0.99183566]
 [0.01478031 0.01768147 0.03958738 ... 0.99250195 0.99183566 1.        ]]


In [53]:
indicesU = pd.Series(user_ids)

def recom(title, cosine_sim):
    recommended_users = []
    idx = indicesU[indicesU == title].index[0]
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_users.append([list(user_ids)[i], i])
        
    return recommended_users

def recU(search, cosine_sim=cosine_simU):
    top = recom(search, cosine_sim)[0]
    ind = indicesU[indicesU==search].index[0]
    ti = users.loc[[ind, top[1]]]
    ti = ti.sort_values(by = top[1], axis = 1, ascending=False)
    exc = [column for column in ti.columns if ti.loc[top[1]][column] > 0]
    ti2 = ti.sort_values(by = ind, axis = 1, ascending=False)
    exc2 = [column for column in ti2.columns if ti2.loc[ind][column] > 0]
    return [x for x in exc2 if x not in exc][:10]

def recommendU(anime_ids):
    names = []
    for animes in anime_ids:
        names.append(anime[anime["MAL_ID"]==int(animes)]["Name"].values[0])
    return names

def recommendUser(user):
    ids = recU(user)
    return recommendU(ids)

recommendUser("2.0")

['Hajime no Ippo',
 'Detective Conan',
 'High School DxD New',
 'Eyeshield 21',
 'Naruto',
 'Tennis no Ouji-sama',
 'Katekyo Hitman Reborn!',
 'One Punch Man',
 'One Punch Man 2nd Season',
 'Boku no Hero Academia 2nd Season']

In [36]:
cosine_simA = cosine_similarity(anime_num, anime_num)
print(cosine_simA)

[[1.         0.98665848 0.99885649 ... 0.50642115 0.08330723 0.01873247]
 [0.98665848 1.         0.99243379 ... 0.45361022 0.07591212 0.01820057]
 [0.99885649 0.99243379 1.         ... 0.4991576  0.08233921 0.01872441]
 ...
 [0.50642115 0.45361022 0.4991576  ... 1.         0.80903078 0.75575516]
 [0.08330723 0.07591212 0.08233921 ... 0.80903078 1.         0.99633013]
 [0.01873247 0.01820057 0.01872441 ... 0.75575516 0.99633013 1.        ]]


In [54]:
indicesA = pd.Series(anime["Name"])

def recommendAnime(title, cosine_sim = cosine_simA):
    recommended_anime = []
    idx = indicesA[indicesA == title].index[0]
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)
    top_10_indices = list(score_series.iloc[1:11].index)
    
    for i in top_10_indices:
        recommended_anime.append(list(anime['Name'])[i])
        
    return recommended_anime

recommendAnime('Cowboy Bebop')

['Hajime no Ippo',
 'Great Teacher Onizuka',
 'Psycho-Pass',
 'Violet Evergarden',
 'Durarara!!',
 'Higurashi no Naku Koro ni',
 'Kekkai Sensen',
 'Slam Dunk',
 'Hyouka',
 'Hellsing Ultimate']

In [55]:
recommendAnime('Jujutsu Kaisen (TV)')

['Shingeki no Kyojin: The Final Season',
 'Tatoeba Last Dungeon Mae no Mura no Shounen ga Joban no Machi de Kurasu Youna Monogatari',
 'Horimiya',
 'Kaifuku Jutsushi no Yarinaoshi',
 'Mushoku Tensei: Isekai Ittara Honki Dasu',
 'SK∞',
 'Ore dake Haireru Kakushi Dungeon',
 'Black Clover',
 'Kumo Desu ga, Nani ka?',
 'Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season Part 2']

In [56]:
recommendUser("823.0")

['Mononoke Hime',
 'Samurai Champloo',
 'Shirobako',
 'Cowboy Bebop',
 'Bakuman. 2nd Season',
 'Uchuu Kyoudai',
 'So Ra No Wo To',
 'Cowboy Bebop: Tengoku no Tobira',
 'Koukaku Kidoutai 2.0',
 'Panty & Stocking with Garterbelt']

In [57]:
recommendAnime('Mononoke Hime')

['Mirai Nikki OVA',
 'Berserk: Ougon Jidai-hen III - Kourin',
 'Tenkuu no Shiro Laputa',
 'Neon Genesis Evangelion: The End of Evangelion',
 'Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku OVA',
 'Kono Subarashii Sekai ni Shukufuku wo! 2: Kono Subarashii Geijutsu ni Shukufuku wo!',
 'Grisaia no Meikyuu: Caprice no Mayu 0',
 'Date A Live II: Kurumi Star Festival',
 'Date A Live: Date to Date',
 'Tokyo Ghoul: "Jack"']